parameters:
#    hexmedia_content.example.class: Hexmedia\ContentBundle\Example

services:
    hexmedia.content.menu.subscriber:
        class: Hexmedia\ContentBundle\Menu\Subscriber
        arguments: [ "@translator" ]
        tags:
            - { name: kernel.event_subscriber }

    hexmedia.content.area_extension:
        class: Hexmedia\ContentBundle\Twig\Extension\AreaExtension
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]
        tags:
            - { name: twig.extension }



