parameters:
#    hexmedia_content.example.class: Hexmedia\ContentBundle\Example

services:
    hexmedia_content.menu.subscriber:
        class: Hexmedia\ContentBundle\Menu\Subscriber
        arguments: [ "@translator" ]
        tags:
            - { name: kernel.event_subscriber }

    hexmedia_content.area_extension:
        class: Hexmedia\ContentBundle\Twig\Extension\AreaExtension
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]
        tags:
            - { name: twig.extension }

    hexmedia_content.fields.media:
        class: Hexmedia\ContentBundle\Form\Fields\MediaType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type, alias: media }


    hexmedia_content.edit_mode.area:
        class: Hexmedia\ContentBundle\EditMode\Area
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: hexmedia.content, alias: area }

    hexmedia_content.edit_mode.page:
        class: Hexmedia\ContentBundle\EditMode\Page
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: hexmedia.content, alias: page }

