HexMediaContentAreaAdd:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:AdminArea:add }
    methods: [GET]
    options:
        expose: true

HexMediaContentAreaCreate:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:AdminArea:create }
    methods: [POST]
    options:
        expose: true


HexMediaContentAreaEdit:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:AdminArea:edit }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentAreaUpdate:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:AdminArea:update }
    methods: [ PUT, POST ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentAreaDelete:
    pattern: /{id}/delete
    defaults: { _controller: HexmediaContentBundle:AdminArea:delete }
    methods: [ POST, PUT, DELETE, GET ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentArea:
    pattern: /
    defaults: { _controller: HexmediaContentBundle:AdminArea:index }
    methods: [ GET ]
    options:
        expose: true

HexMediaContentAreaList:
    pattern: /list/{page}/{sort}/{pageSize}/{sortDirection}
    defaults: { _controller: HexmediaContentBundle:AdminArea:list, page: 1, sort: id, pageSize: %per_page%, sortDirection: asc }
    requirements:
        page: \d+
        pageSize: \d+
        sortDirection: asc|desc
    methods: [ GET ]
    options:
        expose: true