HexMediaContentMediaAdd:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:AdminMedia:add }
    methods: [ GET ]
    options:
        expose: true

HexMediaContentMediaCreate:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:AdminMedia:create }
    methods: [ PUT, POST ]
    options:
        expose: true

HexMediaContentMediaEdit:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:AdminMedia:edit }
    methods: [ GET ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentMediaUpdate:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:AdminMedia:update }
    methods: [ PUT, POST ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentMediaDelete:
    pattern: /{id}/delete
    defaults: { _controller: HexmediaContentBundle:AdminMedia:delete }
    methods: [ POST, PUT, DELETE ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentMediaCustomize:
    pattern: /{id}/customize
    defaults: { _controller: HexmediaContentBundle:Attach:customize }
    requirements:
        id: \d+

HexMediaContentMediaAttach:
    pattern: /attach/{type}/
    defaults: { _controller: HexmediaContentBundle:Attach:attach, type: image }

HexMediaContentMediaAddMultiple:
    pattern: /upload/multiple/
    defaults:  { _controller: HexmediaContentBundle:AdminMedia:multiple }
    options:
        expose: true

HexMediaContentMediaUpload:
    pattern: /upload
    defaults: { _controller: HexmediaContentBundle:Upload:upload }
    options:
        expose: true

HexMediaContentMediaAttach:
    pattern: /attach/{type}/{page}/{sort}/{pageSize}/{sortDirection}
    defaults: { _controller: HexmediaContentBundle:AdminMedia:attach, type: image, page: 1, sort: id, pageSize: %per_page%, sortDirection: asc }
    requirements:
        type: image|video|document
        page: \d+
        pageSize: \d+
        sortDirection: asc|desc
    options:
        expose: true

HexMediaContentMedia:
    pattern: /library
    defaults: { _controller: HexmediaContentBundle:AdminMedia:index }
    methods: [ GET ]
    options:
        expose: true

HexMediaContentMediaList:
    pattern: /list/{page}/{sort}/{pageSize}/{sortDirection}
    defaults: { _controller: HexmediaContentBundle:AdminMedia:list, page: 1, sort: id, pageSize: %per_page%, sortDirection: asc }
    requirements:
        page: \d+
        pageSize: \d+
        sortDirection: asc|desc
    methods: [ GET ]
    options:
        expose: true