HexMediaContentPageList:
    pattern:  /list/{page}/{sort}/{pageSize}/{sortDirection}
    defaults: { _controller: "HexmediaContentBundle:AdminPage:list", page: 1, sort: id, pageSize: %per_page%, sortDirection: asc }
    requirements:
        page: \d+
        pageSize: \d+
        sortDirection: asc|desc
    methods: [ GET, POST ]
    options:
        expose: true

HexMediaContentPage:
    pattern:  /
    defaults: { _controller: "HexmediaContentBundle:AdminPage:index"}
    methods: [ GET, POST ]
    options:
        expose: true

HexMediaContenPageShow:
    pattern:  /{id}/show
    defaults: { _controller: "HexmediaContentBundle:AdminPage:show" }

HexMediaContentPageAdd:
    pattern:  /add
    defaults: { _controller: "HexmediaContentBundle:AdminPage:add" }
    methods: [ GET ]
    options:
        expose: true

HexMediaContentPageCreate:
    pattern:  /add
    defaults: { _controller: "HexmediaContentBundle:AdminPage:create" }
    methods: [ POST]

HexMediaContentPageEdit:
    pattern:  /{id}/edit
    defaults: { _controller: "HexmediaContentBundle:AdminPage:edit" }
    methods: [ GET ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentPageUpdate:
    pattern:  /{id}/edit
    defaults: { _controller: "HexmediaContentBundle:AdminPage:update" }
    methods: [ POST, PUT ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentPageDelete:
    pattern:  /{id}/delete
    defaults: { _controller: "HexmediaContentBundle:AdminPage:delete" }
    methods: [ POST, DELETE ]
    requirements:
        id: \d+
    options:
        expose: true
