HexMediaContentAreaAdd:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:Area:add }
    methods: [GET]
    options:
        expose: true

HexMediaContentAreaCreate:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:Area:create }
    methods: [POST]
    options:
        expose: true


HexMediaContentAreaEdit:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:Area:edit }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentAreaUpdate:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:Area:update }
    methods: [ PUT, POST ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentAreaDelete:
    pattern: /{id}/delete
    defaults: { _controller: HexmediaContentBundle:Area:delete }
    methods: [ POST, PUT ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentArea:
    pattern: /
    defaults: { _controller: HexmediaContentBundle:Area:index }
    methods: [ GET ]
    options:
        expose: true

HexMediaContentAreaList:
    pattern: /list/{page}/{sort}/{pageSize}/{sortDirection}
    defaults: { _controller: HexmediaContentBundle:Area:list, page: 1, sort: id, pageSize: 10, sortDirection: asc }
    requirements:
        page: \d+
        pageSize: \d+
        sortDirection: asc|desc
    methods: [ GET ]
    options:
        expose: true