HexMediaContentAreaAdd:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:Area:add }
    methods: [GET]
    options:
        expose: true

HexMediaContentAreaCreate:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:Area:create }
    methods: [POST]
    options:
        expose: true


HexMediaContentAreaEdit:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:Area:edit }
    methods: [GET]
    options:
        expose: true

HexMediaContentAreaUpdate:
    pattern: /{id}/update
    defaults: { _controller: HexmediaContentBundle:Area:update }
    methods: [ PUT ]
    options:
        expose: true

HexMediaContentAreaDelete:
    pattern: /{id}/delete
    defaults: { _controller: HexmediaContentBundle:Area:delete }
    options:
        expose: true

HexMediaContentArea:
    pattern: /
    defaults: { _controller: HexmediaContentBundle:Area:list }
    methods: [ GET ]
    options:
        expose: true