HexMediaContentMediaAdd:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:Media:add }
    options:
        expose: true

HexMediaContentMediaEdit:
    pattern: /edit/{id}
    defaults: { _controller: HexmediaContentBundle:Media:edit }
    options:
        expose: true

HexMediaContentMediaRemove:
    pattern: /delete/{id}
    defaults: { _controller: HexmediaContentBundle:Media:delete }
    options:
        expose: true

HexMediaContentMediaLibrary:
    pattern: /library
    defaults: { _controller: HexmediaContentBundle:Media:list }
    options:
        expose: true

HexMediaContentMediaCustomize:
    pattern: /customize
    defaults: { _controller: HexmediaContentBundle:Attach:customize }

HexMediaContentMediaAttach:
    pattern: /attach
    defaults: { _controller: HexmediaContentBundle:Attach:attach }

HexMediaContentMediaUpload:
  pattern: /upload
  defaults: { _controller: HexmediaContentBundle:Upload:upload }
  options:
    expose: true

HexMediaContentMediaGalleryAdd:
  pattern: /gallery/add
  defaults: { _controller: HexmediaContentBundle:Gallery:add }
  options:
    expose: true

HexMediaContentMediaGalleryEdit:
  pattern: /gallery/edit
  defaults: { _controller: HexmediaContentBundle:Gallery:edit }
  options:
    expose: true

HexMediaContentMediaGalleryDelete:
  pattern: /gallery/delete
  defaults: { _controller: HexmediaContentBundle:Gallery:delete }
  options:
    expose: true

HexMediaContentMediaGalleryList:
  pattern: /gallery/list
  defaults: { _controller: HexmediaContentBundle:Gallery:list }
  options:
    expose: true

HexMediaContentMediaAttach:
  pattern: /attach
  defaults: { _controller: HexmediaContentBundle:Media:attach }
  options:
    expose: true