HexMediaContentMediaAdd:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:Media:add }
    methods: [ GET ]
    options:
        expose: true

HexMediaContentMediaAdd:
    pattern: /add
    defaults: { _controller: HexmediaContentBundle:Media:create }
    methods: [ PUT, POST ]
    options:
        expose: true

HexMediaContentMediaEdit:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:Media:edit }
    methods: [ GET ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentMediaUpdate:
    pattern: /{id}/edit
    defaults: { _controller: HexmediaContentBundle:Media:update }
    methods: [ PUT, POST ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentMediaDelete:
    pattern: /{id}/delete
    defaults: { _controller: HexmediaContentBundle:Media:delete }
    methods: [ POST, PUT ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentMediaCustomize:
    pattern: /{id}/customize
    defaults: { _controller: HexmediaContentBundle:Attach:customize }
    requirements:
        id: \d+

HexMediaContentMediaAttach:
    pattern: /attach/{type}/
    defaults: { _controller: HexmediaContentBundle:Attach:attach, type: image }

HexMediaContentMediaUpload:
    pattern: /upload
    defaults: { _controller: HexmediaContentBundle:Upload:upload }
    options:
        expose: true

HexMediaContentMediaAttach:
    pattern: /attach
    defaults: { _controller: HexmediaContentBundle:Media:attach }
    options:
        expose: true

HexMediaContentMediaLibrary:
    pattern: /library
    defaults: { _controller: HexmediaContentBundle:Media:index }
    methods: [ GET ]
    options:
        expose: true

HexMediaContentMediaList:
    pattern: /list/{page}/{sort}/{pageSize}/{sortDirection}
    defaults: { _controller: HexmediaContentBundle:Media:list, page: 1, sort: id, pageSize: 10, sortDirection: asc }
    requirements:
        page: \d+
        pageSize: \d+
        sortDirection: asc|desc
    methods: [ GET ]
    options:
        expose: true