HexMediaContentSlider:
    pattern:  /
    defaults: { _controller: "HexmediaContentBundle:Slider:list" }
    methods: [ GET, POST ]
    options:
        expose: true

HexMediaContentSliderAdd:
    pattern:  /add
    defaults: { _controller: "HexmediaContentBundle:Slider:add" }
    methods: [ GET ]
    options:
        expose: true

HexMediaContentSliderCreate:
    pattern:  /add
    defaults: { _controller: "HexmediaContentBundle:Slider:create" }
    methods: [ POST ]
    options:
        expose: true

HexMediaContentSliderEdit:
    pattern:  /{id}/edit
    defaults: { _controller: "HexmediaContentBundle:Slider:edit" }
    methods: [ GET ]

HexMediaContentSliderUpdate:
    pattern:  /{id}/edit
    defaults: { _controller: "HexmediaContentBundle:Slider:update" }
    methods: [ POST, PUT ]
    options:
        expose: true

HexMediaContentSliderDelete:
    pattern:  /{id}/delete
    defaults: { _controller: "HexmediaContentBundle:Slider:delete" }
    methods: [ POST, DELETE ]
    options:
        expose: true
