HexMediaContentSlide:
    pattern:  /{sliderId}
    defaults: { _controller: "HexmediaContentBundle:Slide:index"}
    requirements:
        sliderId: \d+
    options:
        expose: true

HexMediaContentSlideList:
    pattern:  /list/{sliderId}/{page}/{sort}/{pageSize}/{sortDirection}
    defaults: { _controller: "HexmediaContentBundle:Slide:list", page: 1, sort: id, pageSize: 10, sortDirection: asc }
    requirements:
        sliderId: \d+
        page: \d+
        pageSize: \d+
        sortDirection: asc|desc
    options:
        expose: true

HexMediaContentSlideShow:
    pattern:  /{id}/show
    defaults: { _controller: "HexmediaContentBundle:Slide:show" }
    requirements:
        id: \d+

HexMediaContentSlideAdd:
    pattern:  /add/{sliderId}
    defaults: { _controller: "HexmediaContentBundle:Slide:add" }
    requirements:
        sliderId: \d+
    options:
        expose: true

HexMediaContentSlideCreate:
    pattern:  /create/{sliderId}
    defaults: { _controller: "HexmediaContentBundle:Slide:create" }
    options:
        expose: true
    methods: [ POST, PUT ]

HexMediaContentSlideEdit:
    pattern:  /{id}/edit
    defaults: { _controller: "HexmediaContentBundle:Slide:edit" }
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentSlideUpdate:
    pattern:  /{id}/edit
    defaults: { _controller: "HexmediaContentBundle:Slide:update" }
    methods: [ POST, PUT ]
    requirements:
        id: \d+
    options:
        expose: true

HexMediaContentSlideDelete:
    pattern:  /{id}/delete
    defaults: { _controller: "HexmediaContentBundle:Slide:delete" }
    methods: [ POST, DELETE ]
    requirements:
        id: \d+
    options:
        expose: true
