<?php

namespace Hexmedia\ContentBundle\Repository\Doctrine;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;
use Hexmedia\ContentBundle\Repository\AreaRepositoryInterface;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository implements AreaRepositoryInterface
{
    use ListTrait;

    /**
     * @param $name
     * @param $locale
     * @return mixed
     */
    public function getByNameAndPath($name, $path)
    {
        $queryBuilder = $this->createQueryBuilder("a");

        $queryBuilder
            ->where(
                $queryBuilder->expr()->andX(
                    $queryBuilder->expr()->eq('a.name', '?1'),
                    $queryBuilder->expr()->eq('a.path', '?2')
                )
            )
            ->setParameter('1', $name)
            ->setParameter('2', $path);

        try {
            return $queryBuilder->getQuery()->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    public function getByPath($path)
    {
        return $this->findOneByPath($path);
    }

    function getGlobalByName($name)
    {
        // TODO: Implement getGlobalByName() method.
    }
}
