<?php

namespace Hexmedia\ContentBundle\Repository\Doctrine;

use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;
use Hexmedia\ContentBundle\Repository\CategoryRepositoryInterface;
use Hexmedia\AdministratorBundle\Repository\Doctrine\CrudRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends CrudRepository implements CategoryRepositoryInterface
{
    use ListTrait;

}
