<?php

namespace Hexmedia\ContentBundle\Repository\Doctrine;

use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;
use Hexmedia\ContentBundle\Repository\GalleryRepositoryInterface;
use Hexmedia\AdministratorBundle\Repository\Doctrine\CrudRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends CrudRepository implements GalleryRepositoryInterface
{
    use ListTrait;

}
