<?php

namespace Hexmedia\ContentBundle\Repository\Doctrine;

use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;
use Hexmedia\ContentBundle\Repository\PageRepositoryInterface;
use Hexmedia\AdministratorBundle\Repository\Doctrine\CrudRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends CrudRepository implements PageRepositoryInterface {
    use ListTrait;

    /**
     * {@inheritdoc}
     */
    public function createListQueryBuilder($alias) {
        return $this->createQueryBuilder($alias)->where($alias . ".special = 0");
    }
}
