<?php

namespace Hexmedia\ContentBundle\Repository\Doctrine;

use Doctrine\ORM\EntityRepository;
use Hexmedia\ContentBundle\Repository\ScrollerRepositoryInterface;

/**
 * ScrollerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScrollerRepository extends EntityRepository implements ScrollerRepositoryInterface
{

	public function getCount()
	{

	}

	public function getPage($page = 1, $sort = 'id', $pageSize = 10, $sortDirection = 'ASC', $fields = array())
	{

	}

}
